name: Lint code style issues

on:
  pull_request:
    paths:
      - '**.php'

jobs:
  lint-code-styling:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PHP code style issues
        uses: aglipanci/laravel-pint-action@1.0.0
        with:
          testMode: true
          verboseMode: true

      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Check formatting with Prettier
        run: npm run prettier:check
